"""新增<项目>表

Revision ID: 59efe21a42e0
Revises: 22e272149144
Create Date: 2025-12-17 15:12:47.107848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59efe21a42e0'
down_revision = '22e272149144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='项目ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='账户ID'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='项目类型'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='项目图标URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('folder', sa.Text(), nullable=True, comment='项目存储文件夹'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='项目状态'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='项目是否归档'),
    sa.Column('is_recycle', sa.Boolean(), nullable=True, comment='项目是否回收站'),
    sa.Column('is_favor', sa.Boolean(), nullable=True, comment='项目是否收藏'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
