"""新增笔记<note>表

Revision ID: 7e961c863a6e
Revises: 59efe21a42e0
Create Date: 2025-12-17 22:40:54.954980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e961c863a6e'
down_revision = '59efe21a42e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='笔记ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='笔记类型'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='笔记标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='笔记内容'),
    sa.Column('folder', sa.String(length=255), nullable=True, comment='笔记存储文件夹'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='笔记状态'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='笔记是否归档'),
    sa.Column('is_recycle', sa.Boolean(), nullable=True, comment='笔记是否回收站'),
    sa.Column('is_share', sa.Boolean(), nullable=True, comment='笔记是否分享'),
    sa.Column('share_password', sa.String(length=64), nullable=True, comment='笔记分享密码'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
