"""修改note 表中 share_password 的字段长度

Revision ID: cd976d03ab2d
Revises: 7e961c863a6e
Create Date: 2025-12-17 22:53:45.764327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd976d03ab2d'
down_revision = '7e961c863a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('share_password',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_comment='笔记分享密码',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('share_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=64),
               existing_comment='笔记分享密码',
               existing_nullable=True)

    # ### end Alembic commands ###
